In [4]:
import math

In [5]:
math.sqrt(25)

5.0

In [6]:
math.pi

3.141592653589793

In [7]:
import math as mt

In [8]:
mt.sqrt(25)

5.0

In [9]:
from numpy import random

In [10]:
import numpy as np

# uniform random numbers in [0,1]

In [11]:
dataOne = random.rand(5,5)

In [12]:
print(dataOne)

[[0.99895331 0.47491734 0.19448575 0.36254831 0.21119428]
 [0.09756307 0.85798053 0.40059008 0.32652654 0.76454585]
 [0.56062394 0.88590314 0.67332196 0.29395877 0.39119893]
 [0.25920753 0.95725566 0.75031885 0.27204313 0.24426463]
 [0.8035129  0.01507896 0.17534381 0.64978884 0.65930358]]


In [13]:
np.mean(dataOne)

0.49121718664423214

In [17]:
datatwo = random.rand(1,5)

In [18]:
print(datatwo)

[[0.57688876 0.42425099 0.55198627 0.05025958 0.5567933 ]]


In [23]:
math.ceil(0.015)

1

In [24]:
math.floor(0.95)

0

In [25]:
math.pow(0.56,2)

0.31360000000000005

In [31]:
import scipy.stats as st

In [30]:
st.norm.cdf(datatwo)

array([[0.7179927 , 0.66430861, 0.70952112, 0.52004223, 0.71116567]])

In [34]:
st.norm.rvs(datatwo)

array([ 2.99958565,  1.56693117, -0.74945996,  0.37880247,  1.93375706])

In [35]:
st.norm.pdf(datatwo)

array([[0.33778731, 0.36460781, 0.34256874, 0.39843873, 0.34165702]])

In [15]:
print('I Love data Science')

I Love data Science


In [17]:
variableName = 25

In [18]:
variableName1 = 'I Love data Science'

In [19]:
print(variableName1)

I Love data Science


In [20]:
variableName = 25

In [21]:
type(variableName)

int

In [22]:
variableName = 25.0

In [23]:
type(variableName)

float

In [24]:
varOne = 25

In [25]:
varTwo = 25.0

In [26]:
varThree = varOne + varTwo

In [27]:
print(varThree)

50.0


In [68]:
varOne = 25

In [69]:
varTwo = 'Hello'

In [72]:
varThree = (str(varOne) + varTwo)

In [73]:
print(varThree)

25Hello


In [32]:
listOne = [1,2,3,4]

In [33]:
print(listOne[1:3])

[2, 3]


In [44]:
tel = {'jack': 4098, 'sape': 4139}

In [45]:
tel['jack']

4098

In [49]:
Michelle = {'Exam1': 95, 'Exam2': 87, 'Exam3': 85, 'Exam4': 98, 'Exam5': 85}

In [54]:
math.fmod(Michelle['Exam1'], Michelle['Exam2'])

8.0

In [55]:
math.isfinite(Michelle['Exam3'])

True

In [57]:
math.gcd(Michelle['Exam4'], Michelle['Exam5'])

1